### ISSUE TITLE
add an new feature "ignore URL patterns".

### ISSUE THREAD

**Issue by yzwdroid** [MSTEWARDSON/LinkStatus#16]
Hi Matthew,  as described in lab 4 can I add an "ignore URL patterns" feature into your repo. 
- about the ignored file.
the file is a simple text file where each line is either a URL (line starts with http:// or https://) or an optional comment (line starts with #, and can be ignored).

**Comment by MSTEWARDSON** [comment]
Yes sounds good, go ahead. I assigned you to this issue.

**Comment by yzwdroid** [comment]
I have pushed my work to issue-16 branch. Could you please check it? Any problem, let me known.

For testing, run `go run main.go test.txt -i`, the default ignore file is `ignore.txt`

**Comment by MSTEWARDSON** [comment]
Alright thanks.

**Comment by MSTEWARDSON** [comment]
So I have a few suggestions for fully implementing this feature.

1. Add a ignore help message to the helpful information output.
2. Update the ReadMe to show how to use this new feature.

Other then that the code looks good. I like the default ignore file option you added. Good job!

**Comment by yzwdroid** [comment]
I have added a new commit, please check it out.

**Comment by MSTEWARDSON** [comment]
Perfect, thanks! I have now merged your work.
